server:
  port: 8088

#开启日志
logging:
  level:
    com:
      bilibili:
        xm: debug

#数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

#mybatis
mybatis:
  #  Mapper文件存放位置 classpath：指向的是 resources 文件夹
  mapper-locations: classpath:/mapper/*.xml
  #  是否开启驼峰命名，Ming =  m_ing
  map-underscore-to-camel-case: true
  #  包 - 别名，
  type-aliases-package: com.bilibili.xm.pojo
